---
title: "Sketch"
author: "Sunny"
date: "July 20, 2016"
output: html_document
---

```{r packages,echo=FALSE, warning=FALSE, message=FALSE}
setwd("C:/Longitudinal-Project")
#install.packages("crimCV")
library(crimCV)
library(reshape2)
library(dplyr)
#install.packages("mi)
library(mi)
library(ggplot2)
library(gplots)
#install.packages("tigerstats")
library(tigerstats)
library(rgl)
library(car)
```


```{r import, echo=FALSE, warning=FALSE, message=FALSE}
traj_test <- read.csv("C:/Longitudinal-Project/traj_test.csv", stringsAsFactors=FALSE)

```

```{r echo=FALSE, warning=FALSE, message=FALSE}
sub4138 = traj_test[which(traj_test$ID==4138),]
plot(x=sub4138$Age,y = sub4138$C3.Power.s0, type = "l", main = "Subject 4138 (asd)",ylim=c(min(traj_test[,5:1030]),max(traj_test[,5:1030])))
colors=rainbow(100)
for(j in 6:1030){
points(x = sub4138$Age, y = sub4138[,j], type = "l",col = colors[j])
}
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
sub4061 = traj_test[which(traj_test$ID==4061),]
plot(x=sub4061$Age,y = sub4061$C3.Power.s0, type = "l", main = "Subject 4061 (typ)", ylim=c(min(sub4061[,5:1030]),max(sub4061[,5:1030])))
colors=rainbow(100)
for(j in 6:1030){
points(x = sub4061$Age, y = sub4061[,j], type = "l",col = colors[j])
}
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
unique(traj_test$Age)
sub_age3 = subset(traj_test,Age==3)
sub_age6 = subset(traj_test,Age==6)
sub_age9 = subset(traj_test,Age==9)
sub_age12 = subset(traj_test,Age==12)
sub_age18 = subset(traj_test,Age==18)
sub_age24 = subset(traj_test,Age==24)
sub_age36 = subset(traj_test,Age==36)

```

```{r echo=FALSE, warning=FALSE, message=FALSE}
indicator = ifelse(sub_age3$class=="asd", "red",ifelse(sub_age3$class=="typ","green","black"))
heatmap(as.matrix(scale(sub_age3[,5:1030])),RowSideColors = indicator, main = "3 months")
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
indicator = ifelse(sub_age6$class=="asd", "red",ifelse(sub_age6$class=="typ","green","black"))
heatmap(as.matrix(scale(sub_age6[,5:1030])),RowSideColors = indicator, main = "6 months")
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
indicator = ifelse(sub_age9$class=="asd", "red",ifelse(sub_age9$class=="typ","green","black"))
heatmap(as.matrix(scale(sub_age9[,5:1030])),RowSideColors = indicator, main = "9 months")
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
indicator = ifelse(sub_age12$class=="asd", "red",ifelse(sub_age12$class=="typ","green","black"))
heatmap(as.matrix(scale(sub_age12[,5:1030])),RowSideColors = indicator, main = "12 months")
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
indicator = ifelse(sub_age18$class=="asd", "red",ifelse(sub_age18$class=="typ","green","black"))
heatmap(as.matrix(scale(sub_age18[,5:1030])),RowSideColors = indicator, main = "18 months")
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
indicator = ifelse(sub_age24$class=="asd", "red",ifelse(sub_age24$class=="typ","green","black"))
heatmap(as.matrix(scale(sub_age24[,5:1030])),RowSideColors = indicator, main = "24 months")
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
indicator = ifelse(sub_age36$class=="asd", "red",ifelse(sub_age36$class=="typ","green","black"))
heatmap(as.matrix(scale(sub_age36[,5:1030])),RowSideColors = indicator, main = "36 months")
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
traj_test = mutate(traj_test, class2 = ifelse(class=="asd","asd","typ"))
traj_test = mutate(traj_test, class1 = ifelse(class=="typ",1, ifelse(class=="asd", 2,3)))
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
g = ggplot(data=traj_test,aes(x = Age, y = C3.SampE.s0) )
g+geom_point(aes(color=class))+geom_smooth(aes(group=class, color=class))
#g+geom_point(aes(color=class2))+geom_smooth(aes(group=class2, color=class2))
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
g = ggplot(data=traj_test,aes(x = Age, y = C3.SampE.s1) )
g+geom_point(aes(color=class))+geom_smooth(aes(group=class, color=class))
#g+geom_point(aes(color=class2))+geom_smooth(aes(group=class2, color=class2))
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
g = ggplot(data=traj_test,aes(x = Age, y = C3.SampE.s2) )
g+geom_point(aes(color=class))+geom_smooth(aes(group=class, color=class))
#g+geom_point(aes(color=class2))+geom_smooth(aes(group=class2, color=class2))
ggsave("C:/Longitudinal-Project/plots/C3_sampE_s2.jpeg", width=35, height=30, units = "cm")
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
g = ggplot(data=traj_test,aes(x = Age, y = C3.Power.s0) )
g+geom_point(aes(color=class))+geom_smooth(aes(group=class, color=class))
#g+geom_point(aes(color=class2))+geom_smooth(aes(group=class2, color=class2))
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
c3sampes2_typ = polyfitGC(C3.SampE.s2~Age, data = traj_test%>%filter(class2=="typ"),degree = 4)
c3sampes2_asd = polyfitGC(C3.SampE.s2~Age, data = traj_test%>%filter(class2=="asd"),degree = 4)
plot(c3sampes2_asd)
plot(c3sampes2_typ)
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
g = ggplot(data=traj_test,aes(x = Age, y = Fp1.SampE.s0) )
g+geom_point(aes(color=class))+geom_smooth(aes(group=class, color=class))
#g+geom_point(aes(color=class2))+geom_smooth(aes(group=class2, color=class2))
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
g = ggplot(data=traj_test,aes(x = Age, y = Fp1.SampE.s2) )
g+geom_point(aes(color=class))+geom_smooth(aes(group=class, color=class))
#g+geom_point(aes(color=class2))+geom_smooth(aes(group=class2, color=class2))
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
g = ggplot(data=traj_test,aes(x = Age, y = Fp1.RR.s0) )
g+geom_point(aes(color=class))+geom_smooth(aes(group=class, color=class))
#g+geom_point(aes(color=class2))+geom_smooth(aes(group=class2, color=class2))
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
res_asd_typ = data.frame(matrix(NA, nrow=1026, ncol = 8))
names(res_asd_typ)=c("variable","age3", "age6","age9", "age12","age18","age24","age36")
age_list=sort(unique(traj_test$Age))
i = 1
for(var in names(traj_test)[5:1030]){
  test_set = subset(traj_test[,c("Age","class",var)],class != "hra")
  res_asd_typ[i,1]=var
  for(age in unique(test_set$Age)){
    test_age = subset(test_set,Age==age)
    tt = t.test(subset(test_age,class=="asd")[,3],subset(test_age,class=="typ")[,3])
    res_asd_typ[i,which(age_list==age)+1]=tt$p.value
  }
  i = i+1
}
res_asd_typ_bin=res_asd_typ
for(col in c(2:8)){
  res_asd_typ_bin[,col]=ifelse(res_asd_typ_bin[,col]>=0.05,0,1)
}
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
res_asd_typ_bin$age3t12 = apply(res_asd_typ_bin[2:5],1,sum)
res_asd_typ_bin_sub=subset(res_asd_typ_bin,age3t12==4)
res_asd_typ_bin$age3t36 = apply(res_asd_typ_bin[2:8],1,sum)
res_asd_typ_3t36=subset(res_asd_typ_bin,age3t36==7)
dim(res_asd_typ_bin_sub)
dim(res_asd_typ_3t36)
#res_asd_typ_3t36
```


```{r echo=FALSE, warning=FALSE, message=FALSE}
res_asd_hra = data.frame(matrix(NA, nrow=1026, ncol = 8))
names(res_asd_hra)=c("variable","age3", "age6","age9", "age12","age18","age24","age36")
age_list=sort(unique(traj_test$Age))
i = 1
for(var in names(traj_test)[5:1030]){
  test_set = subset(traj_test[,c("Age","class",var)],class != "typ")
  res_asd_hra[i,1]=var
  for(age in unique(test_set$Age)){
    test_age = subset(test_set,Age==age)
    tt = t.test(subset(test_age,class=="asd")[,3],subset(test_age,class=="hra")[,3])
    res_asd_hra[i,which(age_list==age)+1]=tt$p.value
  }
  i = i+1
}
res_asd_hra_bin=res_asd_hra
for(col in c(2:8)){
  res_asd_hra_bin[,col]=ifelse(res_asd_hra_bin[,col]>=0.05,0,1)
}
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
#res_asd_hra_bin$age3t12 = apply(res_asd_hra_bin[2:5],1,sum)
#res_asd_hra_bin_sub=subset(res_asd_hra_bin,age3t12==4)
res_asd_hra_bin$age3t36 = apply(res_asd_hra_bin[2:8],1,sum)
res_asd_hra_3t36=subset(res_asd_hra_bin,age3t36==1)
#dim(res_asd_hra_bin_sub)
dim(res_asd_hra_3t36)
#res_asd_hra_3t36
```


```{r echo=FALSE, warning=FALSE, message=FALSE}
res_typ_hra = data.frame(matrix(NA, nrow=1026, ncol = 8))
names(res_typ_hra)=c("variable","age3", "age6","age9", "age12","age18","age24","age36")
age_list=sort(unique(traj_test$Age))
i = 1
for(var in names(traj_test)[5:1030]){
  test_set = subset(traj_test[,c("Age","class",var)],class != "asd")
  res_typ_hra[i,1]=var
  for(age in unique(test_set$Age)){
    test_age = subset(test_set,Age==age)
    tt = t.test(subset(test_age,class=="typ")[,3],subset(test_age,class=="hra")[,3])
    res_typ_hra[i,which(age_list==age)+1]=tt$p.value
  }
  i = i+1
}
res_typ_hra_bin=res_typ_hra
for(col in c(2:8)){
  res_typ_hra_bin[,col]=ifelse(res_typ_hra_bin[,col]>=0.05,0,1)
}
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
res_typ_hra_bin$age3t12 = apply(res_typ_hra_bin[2:5],1,sum)
res_typ_hra_bin_sub=subset(res_typ_hra_bin,age3t12==4)
res_typ_hra_bin$age3t36 = apply(res_typ_hra_bin[2:8],1,sum)
res_typ_hra_3t36=subset(res_typ_hra_bin,age3t36==7)
dim(res_typ_hra_bin_sub)
dim(res_typ_hra_3t36)
#res_typ_hra_3t36
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
intersect(res_typ_hra_3t36$variable,intersect(res_asd_hra_3t36$variable,res_asd_typ_3t36$variable))
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
